### ISSUE TITLE
May 2018 Hackathon Goals

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#112]
We'll show progress towards these items at the May 2018 Translator Hackathon:

### **Clinical**

* [ ] [Evidence based clinical re-grouping of patients](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/108)
   * [x] Establish [collaboration](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/116) with KFBS+CGI.
   * [x] [smartAPI](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/121) with semantic annotations consumable by reasoners
   * [x] Integrate environmental [exposures data](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/122)
   * [ ] Integrate [socio-environmental exposure data](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/122)

### **Exposures Data**

  * [ ] Expanded temporal and geospatial reach
  * [ ] Semantic annotations for exposures [smartAPI](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/100)

### **Translator APIs and Architecture**

* [ ] [Chemotext3](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/111) smartAPI
* [ ] [smartBag](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/105)
  * [x] [Clinical Toxicogenomic Database](https://github.com/NCATS-Tangerine/smartBag)
     * [x] [Publish](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/126) the endpoint at the Translator smartAPI Registry
  * [x] Build a smartBag prototype of the Orange [bicluster](https://github.com/NCATS-Tangerine/smartBag/issues/2) API.
  * [ ] Support [more sophisticated data relationships.](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/120)
* [x] Generic [Ontology API](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/129)
* [x] [Naming API for Biological Entities](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/133)
* [x] Generic [Translator Knowledge Map API](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/118) - [Rosetta](https://greenncatstranslator.wordpress.com/2018/03/12/rosetta/)
   * [x] Support use of Rosetta within [NIEHS analytic workflow](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/114).
