### ISSUE TITLE
Spring 2019 Hackathon Goals

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#155]
# Green Team - Spring 2019

## ICEES: Scientific Use Cases
  * [ ] Validate integrated feature tables #136, #122
  * [ ] Evaluate ICEES API output
  * [ ] ICEES API usability with respect to Gamma Reasoner - BioLink, Workflows 4 and 5
  * [ ] Expand temporally to include additional years of patient data (2012-2017), #146
  *  [X] Expand feature variables to include additional clinical variables (e.g., pulmonary function tests, FA-relevant measures [metformin, HCT, PLT, WBC]), CMAQ airborne pollutants data, DOT roadway data, and ACS Socioenvironmental data, #146
  * [ ] Develop plans for expanding to include new cohorts (e.g., pain, DILI, diabetes), #146  
  * [ ] Publish approach and preliminary findings, #145 

## X-CTSA Translator Clinical Data Pipeline (aka, CAMP FHIR, FHIR PIT)
  * Present a proof of concept translating EHRs across CTSAs into a single de-identified format sharable as a smartAPI. Publish a pipeline from i2b2 to FHIR to ICEES:
    * [ ] Publish a unified ICEES repo https://github.com/NCATS-Tangerine/icees-api preprocessing https://github.com/xu-hao/datatrans/tree/master/spark #138 
    * [ ] Generate FHIR from i2b2 #137
    * [ ] Document and share across Translator/CTSAs, #140 
    * [ ] Publish software R&D manuscript 

## (Socio)Environmental Exposures Knowledge Sources
  * [x] Document and share, including an architecture diagram #139
  * [x] Create new CMAQ airborne pollutants exposures API #141
  * [X] Create ACS socioenvironmental exposures API #142
     - [ ] Expand service
  * [X] Create DOT roadway exposures API #143 
  * [ ] Document exposures services 
  * [ ] Develop integrated exposures service with visualization capabilities for a nation-wide map of 'environmental profiles' #166

## Translator Platform Services
  * Reasoner Development Toolkit
      - [ ] BioNames 
      - [ ] Onto
      - [ ] CTD
  * [ ] OmniCorp 
      - [ ] #158 Labels
      - [ ] #159 Information Content
      - [ ] #160 Article Similarity
  * [x] Ros [Project](https://github.com/NCATS-Tangerine/ros/projects/1)
      - [x] Develop a Ros CWLTool
      - [x] Develop a CWL workflow for Workflow 5
      - [x] Build a prototype facade for ICEES to (a) implement wf5 modules and (b) map biolink concepts.
  * [ ] UberGraph
  * [ ] Collaborate on development of NIEHS Tox21 API
  * [ ] Develop a link prediction API working with Weifan and Changsung.

## Workflows and TIDBITS (see [NCATS Workflow GitHub Repo](https://github.com/ncats/translator-workflows/issues))
  * [ ]  Workflow 3
       * [ ]  Module execution 
       * [ ]  TIDBITS 
  * [x] Workflow 5
       * [x]  Module execution 
       * [x]  TIDBITS

## Manuscripts
  * [ ]  ICEES JAMIA MS #145 
  * [ ] ICEES JACI MS #162 
  * [ ]  Clinical Data Types MS #144 
  * [ ] CAMP FHIR MS
