### ISSUE TITLE
October Hackathon Prep

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/greendatatranslator#91]
October Hackathon Grocery List:
- **Knowledge Sources** - The Green APIs
  - [x] **Chemo-Bio KS** SPARQL chem2bio2rdf endpoint  @stevencox 
  - [ ] **Clinical Data KS**  @empfff @jameschump see #70 
    - [x] #77 Process for access to real patient data (new network architecture) 
       - [x] @rayi113 and @stevencox to meet with Jan Werner, @jameschump , @xu-hao 
    - [ ] #90 **API Security** architecture prototype
      - [x] Interview and hire contractor
      - [ ] Configure Shibboleth SP
      - [x] Prototype Jupyter notebook(alpha). [NCATS-Tangerine/saml](https://github.com/NCATS-Tangerine/saml)
  - [x] **Environmental Exposures KS**  @lstillwe @mjstealey @hyi @arunacs @ahannaIE see #87 #86 #20 #6 
    - [x] New repository [RENCI/nih-exposures-api](https://github.com/RENCI/nih-exposures-api)
    - [x] ~Mock~ running at proxied public inerface [https://exposures.renci.org/v1/ui/#/default](https://exposures.renci.org/v1/ui/#/default)
  - [x] **Endotypes KS** @krobasky @stevencox @hyi @karafecho see #52 #75  
    - [x] Mock running at https://endotypes.renci.org/v1/ui/
    - [x] New repository [RENCI/nih-endotypes-api](https://github.com/RENCI/nih-endotypes-api)
    - [x] Integrated system invoked from notebook to OpenAPI interface to R model.
  - [x] **Chemotext KS** (Eshelman / Tropsha Group's Medline derived graph database)
- **API Federation** Integrate all Green KSes into Blackboard (CQ notebooks + Reasoner)
  - [x] GitHub Repo [NCATS-Tangerine/greent] (https://github.com/NCATS-Tangerine/greent)
  - [ ] Integrate each from Jupyter to data.
    - [x] ChemBio KS integrated
    - [x] Patient KS integrated
    - [x] Exposure KS integrated
    - [x] Endotype KS integrated
- **Miscellaneous Tech Aims**
  - #84 dependency on @arunacs @ahannaIE 
  - Hong Yi -Python NLP libraries for hackathon
  - Execute a query @empfff @karafecho @krobasky 
  - Capture and analyze team science activities @hyi 
- **Project Management** @rayi113 @davissn30 @kcb13
  - [x] Form Hackathon groups 
  - [x] Initial Hackathon group call 
  - [x] Agenda/Structure of Hackathon
  - [ ] Hackathon Survey

**Comment by hyi** [comment]
@KCB13 I believe I am wrongly assigned for Endotypes service in the list above. It should be most likely assigned to @balhoff and/or @jameschump

**Comment by stevencox** [comment]
Hi @KCB13 and @rayi113. Please have a look at the outline above and let me know if you see problems.

**Comment by stevencox** [comment]
#77 - meeting set up for Thursday to set a path for this.
#75 - preliminary integration of endotype API. Thanks for the extra effort, @hyi

**Comment by stevencox** [comment]
Hackathon completed.
